[package]
name = "haxaw"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
fixed = "1.27.0"
float-ord = "0.3.2"
image = "0.25.1"
imageproc = "0.25.0"
nalgebra = "0.32.5"
stl_io = "0.7.0"
